name: Build and Deploy Rust Lambda

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true

    - name: Install musl-tools
      run: sudo apt-get install -y musl-tools

    # - name: Build
    #   run: |
    #     cd messenger
    #     cargo build --release --target x86_64-unknown-linux-musl
    #     cp ./target/x86_64-unknown-linux-musl/release/messenger ./bootstrap
    #     zip ../rust_lambda.zip bootstrap
    #     cd ..

    - name: Debug - List contents before build
      run: |
        pwd
        ls -R

    - name: Build
      run: |
        cd messenger
        cargo build --release --target x86_64-unknown-linux-musl

    - name: Debug - List contents after build
      run: |
        pwd
        ls -R

    - name: Copy binary
      run: |
        cd messenger
        cp ./target/x86_64-unknown-linux-musl/release/messenger ./bootstrap

    - name: Debug - List contents after copy
      run: |
        pwd
        ls -R

    - name: Create zip
      run: |
        cd messenger
        zip ../rust_lambda.zip bootstrap

    - name: Debug - List contents after zip
      run: |
        pwd
        ls -R

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

#    - name: Upload to S3
#      run: |
#        aws s3 cp rust_lambda.zip s3://${{ secrets.LAMBDA_BUCKET_NAME }}/rust_lambda.zip

#    - name: Update Lambda Function
#      run: |
#        aws lambda update-function-code --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} --s3-bucket ${{ secrets.LAMBDA_BUCKET_NAME }} --s3-key rust_lambda.zip